"""
Streamlit front-end for the Social Media Intelligence Agent.

Runs the multi-agent LangGraph pipeline on user queries and displays:
  - The generated answer (from fine-tuned SmolLM2-360M)
  - Retrieved source posts
  - Agent trace (router decision, HyDE query if used)
  - LangGraph visualization in the sidebar
"""

import os
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

# --- Page config ---
st.set_page_config(
    page_title="Social Media Intelligence Agent",
    page_icon="🔍",
    layout="wide",
)

st.title("🔍 Social Media Intelligence Agent")
st.caption(
    "Multi-agent RAG system powered by LangGraph · "
    "Retrieves from 50k social media posts (Dec 2024) · "
    "Answers generated by fine-tuned SmolLM2-360M"
)


# --- Load graph and model (cached so they only load once) ---

@st.cache_resource(show_spinner="Building agent graph and loading models...")
def load_everything():
    from agents.graph import compiled_graph, save_graph_image
    save_graph_image(compiled_graph, path="graph.png")
    return compiled_graph


graph = load_everything()


# --- Sidebar: graph visualization and info ---
with st.sidebar:
    st.header("Agent Graph")
    if Path("graph.png").exists():
        st.image("graph.png", use_container_width=True)
    else:
        st.info("graph.png not found — run the app once to generate it.")

    st.divider()
    st.markdown("**Models**")
    st.markdown("- Router: `gpt-4o-mini`")
    st.markdown("- HyDE rewriter: `gpt-4o-mini`")
    st.markdown(f"- Retriever: Pinecone (`{os.getenv('PINECONE_INDEX_NAME', 'exorde-week1')}`)")
    st.markdown("- Answer generator: `SmolLM2-360M` (LoRA fine-tuned)")

    st.divider()
    st.markdown("**Dataset**")
    st.markdown("Exorde social media posts · December 2024 · 50k English posts")


# --- Main query interface ---
st.subheader("Ask a question about social media in December 2024")

with st.form("query_form"):
    question = st.text_input(
        "Question",
        placeholder="e.g. What were people saying about cryptocurrency in December 2024?",
    )
    submitted = st.form_submit_button("Run Agent", type="primary")

if submitted and question.strip():
    with st.spinner("Running multi-agent pipeline..."):
        initial_state = {
            "question": question.strip(),
            "rewritten_query": "",
            "retrieved_docs": [],
            "answer": "",
            "use_hyde": False,
            "router_reason": "",
        }
        result = graph.invoke(initial_state)

    # --- Answer ---
    st.subheader("Answer")
    st.write(result["answer"])

    # --- Agent trace ---
    with st.expander("Agent trace", expanded=False):
        st.markdown(f"**Router decision:** `use_hyde = {result['use_hyde']}`")
        st.markdown(f"**Reason:** {result['router_reason']}")
        if result["use_hyde"] and result["rewritten_query"]:
            st.markdown("**HyDE rewritten query:**")
            st.info(result["rewritten_query"])

    # --- Retrieved posts ---
    with st.expander(f"Retrieved posts ({len(result['retrieved_docs'])} found)", expanded=False):
        for i, doc in enumerate(result["retrieved_docs"], start=1):
            meta = doc.metadata
            theme = meta.get("primary_theme", "N/A")
            score = meta.get("score", "N/A")
            timestamp = meta.get("timestamp", "N/A")
            st.markdown(f"**Post {i}** · Theme: `{theme}` · Score: `{score}` · Date: `{timestamp}`")
            st.text(doc.page_content)
            st.divider()

elif submitted and not question.strip():
    st.warning("Please enter a question.")
