"""
Streamlit front-end for the Social Media Intelligence Agent.

Runs the multi-agent LangGraph pipeline on user queries and displays:
  - The generated answer (from fine-tuned SmolLM2-360M)
  - Retrieved source posts
  - Agent trace (HyDE rewritten query)
  - LangGraph visualization in the sidebar
"""

import logging
import os
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

load_dotenv()

# --- Page config ---
st.set_page_config(
    page_title="Social Media Intelligence Agent",
    page_icon="🔍",
    layout="wide",
)

st.title("🔍 Social Media Intelligence Agent")
st.caption(
    "Multi-agent RAG system powered by LangGraph · "
    "Retrieves from 50k social media posts (Dec 2024) · "
    "Answers generated by fine-tuned SmolLM2-360M"
)


# --- Load all resources and compile graph (cached so they only load once) ---

@st.cache_resource(show_spinner="Building agent graph and loading models...")
def load_everything():
    from rag.retriever import PineconeRetriever
    from models.smollm import load_model
    from agents.nodes import AgentNodes
    from agents.graph import build_graph, save_graph_image

    retriever = PineconeRetriever()
    model, tokenizer = load_model()
    nodes = AgentNodes(retriever, model, tokenizer)
    graph = build_graph(nodes)
    save_graph_image(graph, path="graph.png")
    return graph


try:
    graph = load_everything()
except Exception as e:
    logger.exception("Failed to initialise agent resources.")
    st.error(
        f"**Failed to load the agent.** {e}\n\n"
        "Check that `OPENAI_API_KEY` and `PINECONE_API_KEY` are set in your `.env` file "
        "and that the `fine_tuned_model/` directory is present."
    )
    st.stop()


# --- Sidebar: graph visualization and info ---
with st.sidebar:
    st.header("Agent Graph")
    if Path("graph.png").exists():
        st.image("graph.png", use_container_width=True)
    else:
        st.info("graph.png not found — run the app once to generate it.")

    st.divider()
    st.markdown("**Models**")
    st.markdown("- HyDE rewriter: `gpt-4o-mini`")
    st.markdown(f"- Retriever: Pinecone (`{os.getenv('PINECONE_INDEX_NAME', 'exorde-week1')}`)")
    st.markdown("- Answer generator: `SmolLM2-360M` (LoRA fine-tuned)")

    st.divider()
    st.markdown("**Dataset**")
    st.markdown("Exorde social media posts · December 2024 · 50k English posts")


# --- Main query interface ---
st.subheader("Ask a question about social media in December 2024")

with st.form("query_form"):
    question = st.text_input(
        "Question",
        placeholder="e.g. What were people saying about cryptocurrency in December 2024?",
    )
    submitted = st.form_submit_button("Run Agent", type="primary")

if submitted and question.strip():
    result = None
    with st.spinner("Running multi-agent pipeline..."):
        try:
            initial_state = {
                "question": question.strip(),
                "rewritten_query": "",
                "retrieved_docs": [],
                "answer": "",
            }
            result = graph.invoke(initial_state)
        except Exception as e:
            logger.exception("Pipeline failed for question: %s", question.strip())
            st.error(f"**The agent encountered an error.** {e}")

    if result is not None:
        # --- Answer ---
        st.subheader("Answer")
        st.write(result["answer"])

        # --- Agent trace ---
        with st.expander("Agent trace", expanded=False):
            st.markdown("**HyDE rewritten query:**")
            st.info(result["rewritten_query"])

        # --- Retrieved posts ---
        with st.expander(f"Retrieved posts ({len(result['retrieved_docs'])} found)", expanded=False):
            for i, doc in enumerate(result["retrieved_docs"], start=1):
                meta = doc.metadata
                theme = meta.get("primary_theme", "N/A")
                score = meta.get("score", "N/A")
                timestamp = meta.get("timestamp", "N/A")
                st.markdown(f"**Post {i}** · Theme: `{theme}` · Score: `{score}` · Date: `{timestamp}`")
                st.text(doc.page_content)
                st.divider()

elif submitted and not question.strip():
    st.warning("Please enter a question.")
